service: smart-mobility-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: smart-mobility-user-pool

        UsernameAttributes:
          - email

        AutoVerifiedAttributes:
          - email

        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: false
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false

        MfaConfiguration: OFF

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: smart-mobility-client
        UserPoolId:
          Ref: CognitoUserPool

        GenerateSecret: false

        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH

outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient