service: smart-mobility-api

frameworkVersion: '4'

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.11
  timeout: 30
  region: eu-north-1
  stage: dev
  logRetentionInDays: 7

  environment:
    MOBILITY_EVENTS_TABLE: ${self:service}-${sls:stage}-mobility-events

  httpApi:
    authorizers:
      cognitoJwt:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Sub: https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
        audience:
          - Ref: CognitoUserPoolClient

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [MobilityEventsTable, Arn]
  


functions:
  authCheck:
    handler: src/handlers/auth_check.handler

  createMobilityEvent:
    handler: src/handlers/create_mobility_event.handler

resources:
  Resources:
    
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: smart-mobility-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: false
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
        MfaConfiguration: OFF
    
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: smart-mobility-client
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
    
    MobilityEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MOBILITY_EVENTS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
    
    ApiMobility:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: api-mobility
        ProtocolType: HTTP
    
    ApiMobilityStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        ApiId:
          Ref: ApiMobility
        StageName: $default
        AutoDeploy: true
    
    ApiMobilityAuthorizer:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        ApiId:
          Ref: ApiMobility
        AuthorizerType: JWT
        IdentitySource:
          - $request.header.Authorization
        Name: cognito-jwt-mobility
        JwtConfiguration:
          Issuer:
            Fn::Sub: https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}
          Audience:
            - Ref: CognitoUserPoolClient
    
    AuthCheckIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId:
          Ref: ApiMobility
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::GetAtt: [AuthCheckLambdaFunction, Arn]
        PayloadFormatVersion: "2.0"
    
    CreateMobilityEventIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId:
          Ref: ApiMobility
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::GetAtt: [CreateMobilityEventLambdaFunction, Arn]
        PayloadFormatVersion: "2.0"

    AuthCheckRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId:
          Ref: ApiMobility
        RouteKey: GET /auth-check
        Target:
          Fn::Join:
            - /
            - - integrations
              - Ref: AuthCheckIntegration
        AuthorizationType: JWT
        AuthorizerId:
          Ref: ApiMobilityAuthorizer

    CreateMobilityEventRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId:
          Ref: ApiMobility
        RouteKey: POST /mobility/events
        Target:
          Fn::Join:
            - /
            - - integrations
              - Ref: CreateMobilityEventIntegration
        AuthorizationType: JWT
        AuthorizerId:
          Ref: ApiMobilityAuthorizer

    AuthCheckLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Ref: AuthCheckLambdaFunction
        Principal: apigateway.amazonaws.com
        SourceArn:
          Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiMobility}/*/*

    CreateMobilityEventLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Ref: CreateMobilityEventLambdaFunction
        Principal: apigateway.amazonaws.com
        SourceArn:
          Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiMobility}/*/*


  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool

    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient

    ApiMobilityId:
      Value:
        Ref: ApiMobility

    ApiMobilityUrl:
      Value:
        Fn::Sub: https://${ApiMobility}.execute-api.${AWS::Region}.amazonaws.com