service: smart-mobility-simulator

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.11
  region: eu-north-1
  stage: dev
  timeout: 30
  memorySize: 256
  logRetentionInDays: 7

  environment:
    API_MOBILITY_URL:
      Fn::Join:
        - ""
        - - Fn::ImportValue: smart-mobility-${sls:stage}-api-mobility-url
          - /mobility/events
    EVENTS_PER_RUN: ${env:EVENTS_PER_RUN, '10'}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, "6ein230m72do06c2ruijane4uv"}
    COGNITO_USERNAME: ${env:COGNITO_USERNAME, "simulator@urbanmove.local"}
    COGNITO_PASSWORD: ${env:COGNITO_PASSWORD, "Simulator1@"}

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true

functions:
  mobilityEventGenerator:
    handler: handler.lambda_handler
    name: ${self:service}-${sls:stage}-generator
    description: Generates simulated mobility events and posts them to the mobility API
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

